config/routes.rb
Rails.application.routes.draw do
  get 'settings/show'

  get 'settings/update'

  root 'home#index'
  get '/settings', to: 'settings#show'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
  end
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :country

  validates :first_name, :last_name, :street, :city, 
            :zip, :telephone, presence: true

end

app/models/admin_ability.rb
class AdminAbility
  include CanCan::Ability
  def initialize(user)
    if user && user.admin?
      can :access, :rails_admin
      can :manage, :all   
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_and_belongs_to_many :books

  validates :first_name, :last_name, :biography, presence: true
end

app/models/authorization.rb
class Authorization < ApplicationRecord
  belongs_to :user
  
  validates :uid, :provider,  presence: true

  def self.find_for_oauth(auth)
    find_by(provider: auth.provider, uid: auth.uid)
  end
end

app/models/book.rb
class Book < ApplicationRecord
  has_and_belongs_to_many :authors
  belongs_to :category
  has_many :reviews

  validates :title, :short_description, :full_description, :price, :image, presence: true

  #tmp
  scope :bestsellers, -> { where(price: '9.99').limit(6) }
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  has_many :books
end

app/models/country.rb
class Country < ApplicationRecord
  validates :name, presence: true

  has_many :addresses

end

app/models/coupon.rb
class Coupon < ApplicationRecord
    enum coupon_type: [:percent, :fixed_price]

    validates :name, :coupon_type, :code, :discount, :end_date, presence: true

    has_many :orders
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  validates_inclusion_of :month, in: 1..12
  validates_inclusion_of :year, in: 1990..2090
  validates_length_of :card_number, is: 16
  validates_length_of :cvv, is: 3
  validates :month, :year, :cvv, :card_number, presence: true

  belongs_to :user
  has_many :orders
end

app/models/delivery.rb
class Delivery < ApplicationRecord
    validates :cost, :name, presence: true
    
    has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord

  enum state: [:in_progress, :in_queue, :in_delivery, :delivered, :canceled]

  validates :sum, :state, presence: true

  belongs_to :user
	belongs_to :billing_address, class_name: 'Address'
  belongs_to :shipping_address, class_name: 'Address'
  belongs_to :coupon
  belongs_to :delivery
  belongs_to :credit_card
  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  validates :quantity, :total, presence: true

  belongs_to :order
  belongs_to :book
end

app/models/review.rb
class Review < ApplicationRecord
  validates :rating, :text_review, presence: true
  validates_inclusion_of :rating, :in => 1..5
  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :trackable, :validatable,
         :recoverable, :rememberable,  :omniauthable, :omniauth_providers => [:facebook]
  
  has_many :orders       
  belongs_to :billing_address, class_name: 'Address'
  belongs_to :shipping_address, class_name: 'Address'
  has_many :authorizations
  has_many :reviews
  has_one :credit_card


  def self.find_for_oauth(auth, current_user=nil)
    authorization = Authorization.find_for_oauth(auth)
    return authorization.user if authorization

    email = auth.info.email
    return User.new unless email

    user = User.find_by_email(email)
    if user.nil?
      password = Devise.friendly_token[0,10]
      user = User.create!(email: email, password: password, password_confirmation: password)
    end

    user.authorizations.create(provider: auth.provider, uid: auth.uid.to_s)
    user
  end

  def create_authorization(auth)
    authorizations.find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @books = Book.bestsellers
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-default{role: "navigation"}
  / Brand and toggle get grouped for better mobile display
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-ex1-collapse", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'The Bookstore', root_path, class: "navbar-brand"
    / Collect the nav links, forms, and other content for toggling
    .collapse.navbar-collapse.navbar-ex1-collapse
      %ul.nav.navbar-nav
        %li.active
          =link_to t('nav.main'), root_path
        %li
          =link_to t('nav.shop'), '/shop'
      %ul.nav.navbar-nav.navbar-right
        %li
          =link_to '/cart' do
            %i.glyphicon.glyphicon-shopping-cart 
            =t('nav.cart')
        -if user_signed_in?
          %li
            =link_to t('nav.settings'), settings_path
          %li
            =link_to t('nav.orders'), '/orders'
          %li
            =link_to t('nav.logout'), destroy_user_session_path, method: :delete
        -else
          %li
            =link_to t('nav.login'), new_user_session_path
          %li
            =link_to t('nav.registration'), new_user_registration_path
            

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title BookStore
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render "layouts/nav"
    .container
      - flash.each do |name, msg|
        - if msg.is_a?(String)
          %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
            = content_tag :div, msg, :id => "flash_#{name}"
      = yield